#! /usr/bin/env python

"""configuration tool
"""

import os
import sys
import subprocess


def ipConfig():
    if os.getuid() != 0:
        print('sudo required')
        subprocess.call(['sudo', 'python', *sys.argv])
        sys.exit()
    if sys.argv[2] == 'rov':
        config = '''
auto eth0
iface eth0 inet static
address 192.168.1.112
netmask 255.255.255.0
gateway 192.168.1.1'''
        addr = '192.168.1.112'
    else:  # for example argv[2] == 'temp'
        config = '''
auto eth0
iface eth0 inet static
address 192.168.1.113
netmask 255.255.255.0
gateway 192.168.1.1'''
        addr = '192.168.1.113'
    with open('/etc/network/interfaces.d/eth0', 'w') as f:
        f.write(config)
    print(f'Static ip configure done, reboot needed.\nIP set to {addr}')


arg1 = {
    'default': ipConfig,
    'ip': ipConfig,
}


def main():
    return arg1[sys.argv[1] if len(sys.argv) > 1 else 'default']()


if __name__ == '__main__':
    main()
